# Training
launch_name: drumdit_v1_large
device: cuda
epoches: 15
log_dir: "./training_log"
model_cache: "/data/haoyun/mutok/model_cache"
log_frequency: 25
checkpoint_frequency: 3
learning_rate: 1e-4
resume_from_checkpoint: /data/haoyun/mutok/model_cache/drumdit_v1_large/3step.pt
gradient_accumulation_steps: 2
warmup_step: 200

# Dataset
train_dataset_path: "/data/haoyun/mutok/drum_ds"
valid_dataset_path: "/data/haoyun/mutok/drum_test"
num_workers: 2
batch_size: 16


# Codec
sample_rate: 16000
codec_sample_rate: 50
input_dim: 1024
xcodec_config_path: "/data/haoyun/mutok/config_hubert_general.yaml"
xcodec_pretrain_path: "/data/haoyun/mutok/xcodec_hubert_general_audio_v2.pth"
normalize_factor: 6

# Model
seq_len: 1000
encoder_num_layers: 5
decoder_num_layers: 10
num_embedding: 768
num_heads: 8
dropout_p: 0.1
